### ISSUE TITLE
send() function in printer.c

### ISSUE THREAD

**Issue by nazmibojan** [hasyimibhar/escpos-printer#2]
Hello Hasyim,

I have a question about send() function in printer.c.
Where do I find the function in your repository?
Thanks

Regards,
Nazmi

**Comment by nakurr** [comment]
Hi @hasyimibhar 

The send function is located in sys/socket.h (https://pubs.opengroup.org/onlinepubs/7908799/xns/send.html).

Kind regards,
Jonas

**Comment by hasyimibhar** [comment]
@nazmibojan `send` is a system call. You can read about it [here](http://man7.org/linux/man-pages/man2/send.2.html) or [here](https://beej.us/guide/bgnet/html/multi/sendman.html).
